# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: mydatabaseuser
        POSTGRES_PASSWORD: mypassword
    ports:
        - 5432:5432
