# Generated by Django 2.0.1 on 2018-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushTheButtonsMainGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('current_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
