# Generated by Django 2.0.1 on 2019-01-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0004_player_leader'),
        ('push_the_buttons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushthebuttonsmaingame',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushthebuttonsmaingame',
            name='next_to_click',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maingame.Player'),
        ),
        migrations.AlterField(
            model_name='pushthebuttonsmaingame',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group'),
        ),
    ]
