# Generated by Django 2.0.1 on 2019-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_the_buttons', '0002_auto_20190101_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushthebuttonsmaingame',
            name='next_push_before',
            field=models.DateTimeField(null=True),
        ),
    ]
