# Generated by Django 2.0.1 on 2019-01-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maingame', '0004_player_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiklashAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuiklashMainGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('current_score', models.IntegerField(default=0)),
                ('game_ended', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuiklashQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='quiklashanswer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiklash.QuiklashMainGame'),
        ),
        migrations.AddField(
            model_name='quiklashanswer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Player'),
        ),
        migrations.AddField(
            model_name='quiklashanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiklash.QuiklashQuestion'),
        ),
    ]
