# Generated by Django 2.0.1 on 2018-10-23 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
                ('configuration', models.CharField(blank=True, max_length=1024)),
                ('qrCode', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 16, 40, 24, 101747, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Player_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLeader', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Player')),
            ],
        ),
    ]
