# Generated by Django 2.0.1 on 2018-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
