# Generated by Django 2.0.1 on 2018-11-23 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0002_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='moi', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maingame.Group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
