# Generated by Django 2.0.1 on 2019-01-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0003_auto_20181123_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
