# Generated by Django 2.0.1 on 2019-01-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0007_player_last_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
    ]
