# Generated by Django 2.0.1 on 2019-01-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasmaingame',
            name='words_right',
            field=models.IntegerField(default=0),
        ),
    ]
