# Generated by Django 2.0.1 on 2019-01-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maingame', '0008_auto_20190106_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocacheMainGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('current_score', models.IntegerField(default=0)),
                ('game_ended', models.BooleanField(default=False)),
                ('riddles_solved', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GeocacheRiddles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('riddle', models.CharField(max_length=128)),
                ('answer', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
